### ISSUE TITLE
Some returns of eth_getBlockByNumber may be wrong

### ISSUE THREAD

**Issue by frostfrog** [FindoraNetwork/platform#111] opened 2021-11-17 00:43 UTC
### Problem Description
>description:
There is one block with very strange block info when we use `eth_getBlockByNumber`

### Environmental information
>operating system:
N/A
>service:
Forge testnet test
>Code version:

### Steps to reproduce
>1、`curl -H 'Content-Type: application/json' --data '{"method": "eth_getBlockByNumber", "jsonrpc":"2.0", "params":[135134, false], "id": 1}' https://prod-forge.prod.findora.org:8545 | jq .` 
We can get the block hash of 135134 is `0x0ef7bb9a32b72756b5d48f001f78e87798406bce5eaea6dbe09d9f6473a272d1` and we get the stateRoot `0x8133cc87d8f9bc17b3e31deac4cd7fb97e6852a2211e4e3b22fbfccd3874b566`

>2、`curl -H 'Content-Type: application/json' --data '{"method": "eth_getBlockByNumber", "jsonrpc":"2.0", "params":[135135, false], "id": 1}' https://prod-forge.prod.findora.org:8545 | jq .` 
We can find out that the paretHash is `0xac0df09f0699fdaa8af40ce553cd3c03440fc41db47a70ed70e30d86664215f6`, which is **not match** with the previous information.
The stateRoot also changes to `0x1fe00727b579c67555fd07079b36e5b97ce92c2486de6656210f147bf21f3bc3` without any transaction.

>3、`curl -H 'Content-Type: application/json' --data '{"method": "eth_getBlockByNumber", "jsonrpc":"2.0", "params":[135136, false], "id": 1}' https://prod-forge.prod.findora.org:8545 | jq .` 
We can see the parent hash matches the hash of previous block again.
The stateRoot changes back to `0x8133cc87d8f9bc17b3e31deac4cd7fb97e6852a2211e4e3b22fbfccd3874b566` without any transaction. This may be a clue.

**Comment by kevinssgh** [comment] 2021-11-24 19:16
Test results with new node synch:

curl -H 'Content-Type: application/json' --data '{"method": "eth_getBlockByNumber", "jsonrpc":"2.0", "params":[135135, false], "id": 1}' http://localhost:8545

{
   "jsonrpc":"2.0",
   "result":{
      "author":"0x510082967dfa7deba11267b26a6318d07a457b48",
      "difficulty":"0x0",
      "extraData":"0x",
      "gasLimit":"0xffffffff",
      "gasUsed":"0x0",
      **"hash":"0xb3c34af91d86becda4a5d78d703cc4cff25d278f85b0cd955d9f41215903f175",**
      "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "miner":"0x510082967dfa7deba11267b26a6318d07a457b48",
      "number":"0x20fdf",
      **"parentHash":"0x0ef7bb9a32b72756b5d48f001f78e87798406bce5eaea6dbe09d9f6473a272d1",**
      "receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "sealFields":[
         "0x0000000000000000000000000000000000000000000000000000000000000000",
         "0x0000000000000000"
      ],
      "sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "size":"0x200",
      **"stateRoot":"0x8133cc87d8f9bc17b3e31deac4cd7fb97e6852a2211e4e3b22fbfccd3874b566",**
      "timestamp":"0x6184f979",
      "totalDifficulty":"0x0",
      "transactions":[
         
      ],
      "transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "uncles":[
         
      ]
   },
   "id":1
}

curl -H 'Content-Type: application/json' --data '{"method": "eth_getBlockByNumber", "jsonrpc":"2.0", "params":[164355, false], "id": 1}' http://localhost:8545

{
   "jsonrpc":"2.0",
   "result":{
      "author":"0xeac5792572eb726aa0dba9a7afa9757f8063c6c9",
      "difficulty":"0x0",
      "extraData":"0x",
      "gasLimit":"0xffffffff",
      "gasUsed":"0x0",
      **"hash":"0xb3c31bf26f32f95d16381cda958384dde49c4a70e8cec6e39005f6d04968f175",**
      "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "miner":"0xeac5792572eb726aa0dba9a7afa9757f8063c6c9",
      "number":"0x28203",
      **"parentHash":"0xac0df09f0699fdaa8af40ce553cd3c03440fc41db47a70ed70e30d86664215f6",**
      "receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "sealFields":[
         "0x0000000000000000000000000000000000000000000000000000000000000000",
         "0x0000000000000000"
      ],
      "sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "size":"0x200",
      **"stateRoot":"0x1fe00727b579c67555fd07079b36e5b97ce92c2486de6656210f147bf21f3bc3",**
      "timestamp":"0x6188d1fe",
      "totalDifficulty":"0x0",
      "transactions":[
         
      ],
      "transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "uncles":[
         
      ]
   },
   "id":1
}

After height 164355 another query for block 135135 results in the following:

curl -H 'Content-Type: application/json' --data '{"method": "eth_getBlockByNumber", "jsonrpc":"2.0", "params":[135135, false], "id": 1}' http://localhost:8545

{
   "jsonrpc":"2.0",
   "result":{
      "author":"0xeac5792572eb726aa0dba9a7afa9757f8063c6c9",
      "difficulty":"0x0",
      "extraData":"0x",
      "gasLimit":"0xffffffff",
      "gasUsed":"0x0",
      **"hash":"0xb3c31bf26f32f95d16381cda958384dde49c4a70e8cec6e39005f6d04968f175",**
      "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "miner":"0xeac5792572eb726aa0dba9a7afa9757f8063c6c9",
      "number":"0x28203",
      **"parentHash":"0xac0df09f0699fdaa8af40ce553cd3c03440fc41db47a70ed70e30d86664215f6",**
      "receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "sealFields":[
         "0x0000000000000000000000000000000000000000000000000000000000000000",
         "0x0000000000000000"
      ],
      "sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "size":"0x200",
      **"stateRoot":"0x1fe00727b579c67555fd07079b36e5b97ce92c2486de6656210f147bf21f3bc3",**
      "timestamp":"0x6188d1fe",
      "totalDifficulty":"0x0",
      "transactions":[
         
      ],
      "transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "uncles":[
         
      ]
   },
   "id":1
}

The result would indicate that the original block 135135 was overwritten by the block at height 164355. This is why the state root and parent hash weren't consistent with the blocks 135134 and 135136

**Comment by kevinssgh** [comment] 2021-11-25 01:19
Root Cause:

The block hash (H256 type) is used as a key/index for the block. This implemented in an external lib (fixed-hash) and has an implementation of the display trait as follows:

	```
	impl $crate::core_::fmt::Display for $name {
			fn fmt(&self, f: &mut $crate::core_::fmt::Formatter) -> $crate::core_::fmt::Result {
				$crate::core_::write!(f, "0x")?;
				for i in &self.0[0..2] {
					$crate::core_::write!(f, "{:02x}", i)?;
				}
				$crate::core_::write!(f, "…")?;
				for i in &self.0[$n_bytes - 2..$n_bytes] {
					$crate::core_::write!(f, "{:02x}", i)?;
				}
				Ok(())
			}
		}
```

As a result the keys being used in the block store are shortened in the following format:

FindoraHashToBlock_0xb3c3…f175

The first and last 2 bytes are used as the key for the block. The 2 blocks mentioned above (135135, 164355) have the same first and last 2 bytes as part of their block hash and were indexed in the same position. The later block 164355 overwrote the previous one.

**Comment by jianwel** [comment] 2021-11-25 05:12
@kevinssgh you may see whether we can use the block number instead of the hash as the index when storing them.

**Comment by kevinssgh** [comment] 2021-11-30 18:24
Fix has been merged

**Closed by kevinssgh** 2021-11-30 18:24 UTC
